### ISSUE TITLE
The reason why your js files are minified

### ISSUE THREAD

**Issue by nurgasemetey** [joviefung/amazon-ses-template-management-page#1]
I am curious why you did minimize them

**Comment by joviefung** [comment]
I am not doing it intentionally but it is the default setting of vue-cli to build production code.

**Comment by nurgasemetey** [comment]
It could be good to not minimize them because people might have doubts about source code.

**Comment by joviefung** [comment]
I have disabled minify and updated the page.. please check. : )
If you really need to read the source code you can go to
[https://github.com/joviefung/amazon-ses-template-management](https://github.com/joviefung/amazon-ses-template-management)
If you want to run the page locally you can just download the source code, `npm install` and `npm run serve`.

**Comment by nurgasemetey** [comment]
Sorry if I was suspiciouos, props to you :-)
